# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191124_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleuser',
            old_name='onid',
            new_name='username',
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='email',
            field=models.CharField(default='notused', max_length=25, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
