# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191124_1833'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scheduleuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='scheduleuser',
            old_name='username',
            new_name='onid',
        ),
        migrations.RemoveField(
            model_name='scheduleuser',
            name='email',
        ),
    ]
