# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20191124_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is_staff'),
            preserve_default=False,
        ),
    ]
