# Generated by Django 2.2.6 on 2019-10-23 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onid', models.CharField(max_length=25, unique=True, verbose_name='ONID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=25, verbose_name='phone number')),
                ('creator_privelege', models.BooleanField(verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=25, verbose_name='date reserved')),
                ('start_time', models.TimeField(max_length=25, verbose_name='start time')),
                ('end_time', models.TimeField(max_length=25, verbose_name='end time')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('num_people', models.IntegerField(verbose_name='max number of people')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.User')),
            ],
            options={
                'unique_together': {('user', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('path', models.CharField(max_length=500, verbose_name='path')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Reservation')),
            ],
            options={
                'unique_together': {('name', 'path')},
            },
        ),
    ]
