# Generated by Django 2.2.6 on 2019-10-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=25, verbose_name='Date reserved')),
                ('start_time', models.TimeField(max_length=25, verbose_name='Start time')),
                ('end_time', models.TimeField(max_length=25, verbose_name='end time')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('num_people', models.IntegerField(verbose_name='max number of people')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onid', models.CharField(max_length=25, verbose_name='ONID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone_num', models.CharField(max_length=25, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Student')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('file_type', models.CharField(max_length=50, verbose_name='File type')),
                ('location', models.CharField(max_length=500, verbose_name='File location')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Reservation')),
            ],
        ),
    ]
