# Generated by Django 2.2.6 on 2019-10-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(max_length=50, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(max_length=50, verbose_name='start time'),
        ),
    ]
