# Generated by Django 2.2.6 on 2019-10-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_slot_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Subject',
            new_name='subject',
        ),
    ]
