# Generated by Django 2.2.6 on 2019-10-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20191028_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='end_time',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='owner',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_time',
            new_name='StartTime',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='subject',
            new_name='Subject',
        ),
    ]
