# Generated by Django 2.2.6 on 2019-10-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20191028_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creator_privelege',
            new_name='creator_privilege',
        ),
    ]
