# Generated by Django 2.2.6 on 2019-11-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_credentialsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='EndTime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='StartTime',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='Subject',
        ),
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(default='work', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
