# Generated by Django 2.2.6 on 2019-10-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creator_privelege',
            new_name='creator_privilege',
        ),
    ]
